package:
  name: httpfox
  version: 2.0.2
  epoch: 1
  description: a website to map http error codes to foxes
  copyright:
    - license: GPL-2.0-only
      paths:
        - "*"

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - build-base
      - wolfi-baselayout
      - ca-certificates-bundle
      - pkgconf
      - busybox
      - nodejs-22
      - yarn
      - git
      - rust
pipeline:
  - name: Build Httpfox
    runs: |
      FOX_HOLE="${{targets.destdir}}/"
      EXEC_DIR="${{targets.destdir}}/usr/bin"
      TARGETDIR="/var/cache/melange/httpfox"
      mkdir -p "${EXEC_DIR}"
      rm -rf .cargo
      RUSTFLAGS="-C target-feature=+crt-static" cargo build --target x86_64-unknown-linux-gnu --release --target-dir "${TARGETDIR}"
      cd static_src
      yarn && yarn compile:prod
      cd ..
      cp -v "${TARGETDIR}/x86_64-unknown-linux-gnu/release/httpfox" "${EXEC_DIR}"
      cp -rv static    "${FOX_HOLE}/static"
      cp -rv templates "${FOX_HOLE}/templates"
      cp -rv data "${{targets.destdir}}/data"
